export type details = {
  appointment_date: string,
  examination_type: string,
  tests_conducted: string,
  prescribed_medications: string,
  result: string,
};

export type historyItem = {
  id: string,
  date: string,
  department: string,
  details: details,
  files: string[],
};

export type historyType = historyItem[];

export const history = [
  {
    id: '0001',
    date: '01.06.2024',
    department: 'Nöroloji',
    details: {
      appointment_date: '01.06.2024',
      examination_type: 'Nöroloji',
      tests_conducted: 'Beyin Tomografisi',
      prescribed_medications: 'Sumatriptan (100 mg)',
      result: 'Migren Tanısı',
    },
    files: ['/photo1.jpg', '/photo2.jpg', '/photo3.jpg'],
  },
  {
    id: '0002',
    date: '02.06.2024',
    department: 'Kardiyoloji',
    details: {
      appointment_date: '02.06.2024',
      examination_type: 'Kardiyoloji',
      tests_conducted: 'EKG',
      prescribed_medications: 'Aspirin (81 mg)',
      result: 'Kalp Ritm Bozukluğu',
    },
    files: ['/photo2.jpg', '/photo3.jpg', '/photo1.jpg'],
  },
  {
    id: '0003',
    date: '03.06.2024',
    department: 'Dermatoloji',
    details: {
      appointment_date: '03.06.2024',
      examination_type: 'Dermatoloji',
      tests_conducted: 'Cilt Biyopsisi',
      prescribed_medications: 'Hidrokortizon (50 mg)',
      result: 'Egzama',
    },
    files: ['/photo3.jpg', '/photo1.jpg', '/photo2.jpg'],
  },
  {
    id: '0004',
    date: '04.06.2024',
    department: 'Gastroenteroloji',
    details: {
      appointment_date: '04.06.2024',
      examination_type: 'Gastroenteroloji',
      tests_conducted: 'Endoskopi',
      prescribed_medications: 'Pantoprazol (40 mg)',
      result: 'Gastrit',
    },
    files: ['/photo1.jpg', '/photo3.jpg', '/photo2.jpg'],
  },
  {
    id: '0005',
    date: '05.06.2024',
    department: 'Endokrinoloji',
    details: {
      appointment_date: '05.06.2024',
      examination_type: 'Endokrinoloji',
      tests_conducted: 'Tiroid Ultrasonu',
      prescribed_medications: 'Levotiroksin (75 mcg)',
      result: 'Hipotiroidi',
    },
    files: ['/photo2.jpg', '/photo1.jpg', '/photo3.jpg'],
  },
  {
    id: '0006',
    date: '06.06.2024',
    department: 'Ortopedi',
    details: {
      appointment_date: '06.06.2024',
      examination_type: 'Ortopedi',
      tests_conducted: 'MR',
      prescribed_medications: 'Diklofenak (50 mg)',
      result: 'Menisküs Yırtığı',
    },
    files: ['/photo3.jpg', '/photo2.jpg', '/photo1.jpg'],
  },
  {
    id: '0007',
    date: '07.06.2024',
    department: 'Nefroloji',
    details: {
      appointment_date: '07.06.2024',
      examination_type: 'Nefroloji',
      tests_conducted: 'Böbrek Ultrasonu',
      prescribed_medications: 'Furosemid (20 mg)',
      result: 'Böbrek Taşı',
    },
    files: ['/photo1.jpg', '/photo2.jpg', '/photo3.jpg'],
  },
  {
    id: '0008',
    date: '08.06.2024',
    department: 'Göz Hastalıkları',
    details: {
      appointment_date: '08.06.2024',
      examination_type: 'Göz Muayenesi',
      tests_conducted: 'Göz Tansiyonu',
      prescribed_medications: 'Timolol (0.5%)',
      result: 'Glokom',
    },
    files: ['/photo2.jpg', '/photo3.jpg', '/photo1.jpg'],
  },
  {
    id: '0009',
    date: '09.06.2024',
    department: 'Kulak Burun Boğaz',
    details: {
      appointment_date: '09.06.2024',
      examination_type: 'KBB Muayenesi',
      tests_conducted: 'Odyometri',
      prescribed_medications: 'Betahistin (16 mg)',
      result: 'Meniere Hastalığı',
    },
    files: ['/photo3.jpg', '/photo1.jpg', '/photo2.jpg'],
  },
  {
    id: '0010',
    date: '10.06.2024',
    department: 'Psikiyatri',
    details: {
      appointment_date: '10.06.2024',
      examination_type: 'Psikiyatri',
      tests_conducted: 'Psikolojik Değerlendirme',
      prescribed_medications: 'Sertralin (50 mg)',
      result: 'Anksiyete Bozukluğu',
    },
    files: ['/photo1.jpg', '/photo3.jpg', '/photo2.jpg'],
  },
  {
    id: '0011',
    date: '11.06.2024',
    department: 'Üroloji',
    details: {
      appointment_date: '11.06.2024',
      examination_type: 'Üroloji',
      tests_conducted: 'Prostat Ultrasonu',
      prescribed_medications: 'Tamsulosin (0.4 mg)',
      result: 'Prostat Büyümesi',
    },
    files: ['/photo2.jpg', '/photo1.jpg', '/photo3.jpg'],
  },
  {
    id: '0012',
    date: '12.06.2024',
    department: 'Kadın Hastalıkları',
    details: {
      appointment_date: '12.06.2024',
      examination_type: 'Jinekolojik Muayene',
      tests_conducted: 'Pelvik Ultrason',
      prescribed_medications: 'Kombine Oral Kontraseptif',
      result: 'Polikistik Over Sendromu',
    },
    files: ['/photo3.jpg', '/photo2.jpg', '/photo1.jpg'],
  },
  {
    id: '0013',
    date: '13.06.2024',
    department: 'Radyoloji',
    details: {
      appointment_date: '13.06.2024',
      examination_type: 'Radyoloji',
      tests_conducted: 'Röntgen',
      prescribed_medications: 'Ağrı Kesici',
      result: 'Kırık',
    },
    files: ['/photo1.jpg', '/photo2.jpg', '/photo3.jpg'],
  },
  {
    id: '0014',
    date: '14.06.2024',
    department: 'Acil Servis',
    details: {
      appointment_date: '14.06.2024',
      examination_type: 'Acil Muayene',
      tests_conducted: 'Kan Testi',
      prescribed_medications: 'İbuprofen (400 mg)',
      result: 'Enfeksiyon',
    },
    files: ['/photo2.jpg', '/photo3.jpg', '/photo1.jpg'],
  },
  {
    id: '0015',
    date: '15.06.2024',
    department: 'Fizyoterapi',
    details: {
      appointment_date: '15.06.2024',
      examination_type: 'Fizik Tedavi',
      tests_conducted: 'Fiziksel Değerlendirme',
      prescribed_medications: 'Fizik Tedavi Egzersizleri',
      result: 'Kas Zayıflığı',
    },
    files: ['/photo3.jpg', '/photo1.jpg', '/photo2.jpg'],
  },
];
